# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests selenium faker
          pip install webdriver-manager==3.5.2
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: python-flake8
        # You may pin to the exact commit or the version.
        # uses: julianwachholz/flake8-action@75749239077651dfd0ecbe405899cdcb0673ee8f
        uses: julianwachholz/flake8-action@v2.0.2
        with:
          # The name of the check to add annotations to. Generally the same as the job that uses this action
          checkName:
          # Path to use for flake8
          path: # optional, default is .
          # Package names of flake8 plugins passed on to the `pip install` command.
          plugins: # optional, default is
          # Specify a config file for flake8
          config: # optional
          # Used for internal tests
          isTest: # optional, default is false
      - name: Test with pytest
        run: |
          pytest
