# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: workflow_pytest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests selenium faker allure-pytest allure-python-commons
          pip install webdriver-manager==3.5.2
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          pytest  --alluredir /tmp/allure_results
      - name: Allure report
        # You may pin to the exact commit or the version.
        # uses: afiore/action-allure-report@e43ebd6f4f4c74b07b1eb02f042902bbe6786a19
        uses: afiore/action-allure-report@v0.1.0
        with:
          # Allure test result data dir
          results-dir: /tmp/allure_results
          # Allure report target dir
          report-dir: /tmp/allure_results

