# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: workflow_pytest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests selenium faker allure-pytest allure-python-commons
          pip install webdriver-manager==3.5.2
          pip install -r requirements.txt
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Test with pytest
        run: |
          pytest  --alluredir /tmp/allure_results
          
      - name: Install allure
        run: pip install allure-pytest allure-python-commons
      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
          
      - name: Check out branch gh-pages
        uses: actions/checkout@v2
        with:
          ref: 'gh-pages'
          
      - name: Copy needed files
        run: |
          mkdir -p result
          cp -r . /result
          ls -l result
          
      - run: git init
        working-directory: result

      - name: Push
        uses: actions-js/push@master
        with:
          repository: gonuskus/gonuskus.github.io
          directory: result
          message: ${{ github.event.head_commit.message }}
          force: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
